[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
eth-rpc-url = "http://localhost:8545" # using a local Evmos node

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
